import sqlite3
database = 'techshop.db'
con = sqlite3.connect('techshop.db')
cur = con.cursor()

# cur.execute('''create table phones (company text , fullname text , memory text , color text , date text , size text , weight text , simcard text ,  screensize text , screenresolution text , operatingsystem text , chipset text , gpu text , ram text ,  additionalmemory text , maincamera text ,  video text , selfiecamera text , selfievideo text , bluthooth text , gps text , nfc text , fmradio text ,  port text ,sizemah text)''')
# cur.execute('''INSERT INTO phones (company , fullname              , memory            , color                                            , date             , size                , weight  , simcard      ,  screensize  , screenresolution , operatingsystem , chipset                   , gpu                           , ram    ,  additionalmemory , maincamera   ,  video                                                                                                                          , selfiecamera , selfievideo                                       , bluthooth       , gps                                            , nfc , fmradio   ,  port , sizemah ) 
#                           VALUES  ("Apple" , "Apple iPhone 13 pro" , "128/256/512/1TB" , "Graphite/Silver/Gold/Sierra Blue/Alphine Green" , "2021 September" , "146.7x71.5x7.7 mm" , "204 g" , "Single SIM" , "6.1 inches" , "1170 x 2532"    , "iOS 15"        , "Apple A15 Bionic (5 nm)" , "Apple GPU (5-core graphics)" , "6 GB" , "NO"              , "12+12+12MP" ,  "4K@24/30/60fps, 1080p@30/60/120/240fps, 10 bit HDR, Dolby Vision HDR (up to 60fps), ProRes, Cinematic mode, stereo sound rec" , "12 MP"      , "4K@24/25/30/60fps, 1080p@30/60/120fps, gyro-EIS" , "5.0, A2DP, LE" , "Yes, with A-GPS, GLONASS, GALILEO, BDS, QZSS" , "YES" , "NO"    , "NO"  , "Li-Ion 3095 mAh") ''')

cur.execute('''INSERT INTO phones (company , fullname          , memory    , color                                      , date           , size                , weight  , simcard      ,  screensize  , screenresolution , operatingsystem , chipset                   , gpu                           , ram    ,  additionalmemory , maincamera   ,  video                                                                                        , selfiecamera , selfievideo                                       , bluthooth       , gps                                            , nfc   , fmradio ,  port , sizemah ) 
                          VALUES  ("Apple" , "Apple iPhone 12" , "128/256" , "Midnight/Green/Blue/White/Red/Purple"     , "2020 October" , "146.7x71.5x7.7 mm" , "164 g" , "Single SIM" , "6.1 inches" , "1170 x 2532"    , "iOS 13"        , "Apple A14 Bionic (5 n)" , "Apple GPU (4-core graphics)" , "4 GB" , "NO"              , "12+12MP" ,  "4K@24/30/60fps, 1080p@30/60/120/240fps, HDR, Dolby Vision HDR (up to 30fps), stereo sound rec"  , "12 MP"      , "4K@24/25/30/60fps, 1080p@30/60/120fps, gyro-EIS" , "5.0, A2DP, LE" , "Yes, with A-GPS, GLONASS, GALILEO, BDS, QZSS" , "YES" , "NO"    , "NO"  , "Li-Ion 2815 mAh") ''')

con.commit()
con.close()